### ISSUE TITLE
[Request] Support for VOX?

### ISSUE THREAD

**Issue by Fearcatcher** [Nosskirneh/NextUp-Public#10]
Is it hard to made?

https://itunes.apple.com/app/apple-store/id916215494?pt=83836&ct=VOX_iPhone_page&mt=8&at=11l565

**Comment by Nosskirneh** [comment]
Doesn’t seem to be too difficult. I’ll look into this some more later.

**Comment by Nosskirneh** [comment]
Added in beta3 (to be released soon).
