### ISSUE TITLE
Fix for iPhone X

### ISSUE THREAD

**Issue by willemlangezaal** [Nosskirneh/NextUp-Public#12]
When I use nextup together with ColorFlow fullscreen, the next up section is just a littlebit off screen. Please fix this beceause it just don’t fit well at the moment. Thanks.

**Comment by Nosskirneh** [comment]
I'm thinking about adding an option to remove the "NextUp" label. Would that provide enough space for it all to fit? (I don't have an iPhone X to check).

**Comment by willemlangezaal** [comment]
Yes, I think that’s just enough. Thanks!

**Comment by Nosskirneh** [comment]
Implemented in beta8 of NextUp 2. Would you please test to see if this is enough for it to not get cut off?

**Comment by willemlangezaal** [comment]
Yes please

Verstuurd vanaf mijn iPhone

**Comment by Nosskirneh** [comment]
I realize that I phrased that badly. The beta is available at my repo, feel free to test if it’s enough :)

**Comment by willemlangezaal** [comment]
Done that thanks

Verstuurd vanaf mijn iPhone
