### ISSUE TITLE
Masq Support

### ISSUE THREAD

**Issue by delon5** [Nosskirneh/NextUp-Public#13]
Masq allows you to theme album artwork.

This repo has an update for ios 11 & 12 https://ndoizo.ca

If using custom artwork no artwork displays in nextup 2.

**Comment by KyleWTF** [comment]
I agree this is needed as Masq is a beautiful tweak and i'd love to use with nextup 2.

**Comment by ahanank** [comment]
Yup, would love support for Masq 👍

**Comment by Nosskirneh** [comment]
Support is essentially done since a month ago, but I can't get hold of candoizo. It's supposed to go live on his repo.
