### ISSUE TITLE
Haptic feedback

### ISSUE THREAD

**Issue by hugomendezp** [Nosskirneh/NextUp-Public#16]
I have disabled both haptic feedback and I have done a respring and it still exists, I have tried it several times and it does not work for me, this is one of my favorite tweaks, thanks for your enormous work

**Comment by Nosskirneh** [comment]
Hi!

I realized that the setting for disabling the skip button's haptic feedback doesn't work. The haptic feedback setting for the other media buttons should work – or do you have problems with this as well?

**Comment by hugomendezp** [comment]
Hi!
Yes! The media buttons settings works fine, no problem with that

Thanks for reply! you do an amazing job
Congrats
On Apr 22, 2019, 23:27 -0500, Andreas Henriksson <notifications@github.com>, wrote:

Hi!

I realized that the setting for disabling the skip button's haptic feedback doesn't work. The haptic feedback setting for the other media buttons should work – or do you have problems with this as well?

**Comment by Nosskirneh** [comment]
Thank you! This is fixed in beta5 of NextUp 2. A new beta of NextUp with this will come soon.
