### ISSUE TITLE
Next Up 2 does not work at all

### ISSUE THREAD

**Issue by LilPenguinTV** [Nosskirneh/NextUp-Public#18]
I install Nextup 2 on my Iphone 8+ on ios 12.0.1 and nothing happens on the lockscreen.

**Comment by Nosskirneh** [comment]
What about Control Center?
What version of NextUp 2 are you using? What version of RocketBootstrap do you have installed?
What media client are you using?

Also, just to make sure: you have activated a trial license, right?

**Comment by LilPenguinTV** [comment]
I have activated the license. Control center has nothing. i have the rocketbootstrap from rpetri and im using spotify.

**Comment by Nosskirneh** [comment]
Are you using Chimera or unc0ver, and what version of it?

**Comment by LilPenguinTV** [comment]
unc0ver 3.0.1

**Comment by Nosskirneh** [comment]
Not sure what could be the culprit. Please try to disable all other tweaks (using iCleaner Pro) to see if there is anything conflicting. Also please try to reinstall RocketBootstrap; I've sometimes seen that solving issues like these.

**Comment by LilPenguinTV** [comment]
still doesnt work. i have the trial license activated. I would love to have this work as i have seen it on a youtube video and it looks awesome

**Comment by Nosskirneh** [comment]
Glad to hear! Okay, are you using NoSub or anything like that for Spotify? Some users have reached out with similar issues and that have sometimes been the culprit.

You could try another tweak that is using RocketBootstrap, like ChatHeads or Bazzi, to see if it is RocketBootstrap not working on your device or if tweaks are not executing within Spotify.

You could also try to play music from the Music app to see if that works.

**Comment by LilPenguinTV** [comment]
i am using bdayspotify 2 but i have tried uninstalling that and just using the base spotify and that didnt work. i am using mitsuha infinity and that uses rocketbootstrap so i know that rocketbootstrap is working

**Comment by Nosskirneh** [comment]
Okay. Just to make sure, please try to disable *all* other tweaks and see if that works, it could be something you're not thinking of.

Again, try to play music from the Music app to see if that works.

**Comment by LilPenguinTV** [comment]
ok so i guess something was wrong with my spotify so i uninstalled spotify and reinstalled. sorry for this 30 minute conversation for this little problem. but it works now and im gonna purchase this because its awesome!!

**Comment by LilPenguinTV** [comment]
ok so actually i think its the bdayspotify tweak but im not sure yet

**Comment by LilPenguinTV** [comment]
ok so nevermind everything i just said. its a tweak that i have installed so im going to try and figure it out

**Comment by Nosskirneh** [comment]
Glad you're on to it! Please let me know which one it is, might be good for future reference.

**Comment by LilPenguinTV** [comment]
ok so i figured it out. its Emojiport (ios 12) and emojiattributes. i dont know why this affects it. i have everything else activated and nextup 2 works with all those except these two.

**Comment by Nosskirneh** [comment]
Hmm, no idea why those would interfere with NextUp. I have no device on iOS 12.0.x to test it on.

**Comment by LilPenguinTV** [comment]
i dont know. i dont really use those newer emojis anyways so i guess ill just leave it un checked and buy the nextup 2 license because it seems more practical.

**Comment by Nosskirneh** [comment]
Glad to hear! Let me know if you get any other issue :)
