### ISSUE TITLE
Hide on Empty not working with individual tracks

### ISSUE THREAD

**Issue by ahanank** [Nosskirneh/NextUp-Public#20]
When one searches and plays a track on Spotify (haven’t tried any other streaming service), the ‘hide on empty’ feature doesn’t engage. Instead, there is blank space where the NextUp queue normally would be with no text or info.

**Comment by ahanank** [comment]
Update: Seems like ‘Hide on Empty’ function isn’t working at all. That might be it. Because I ended a playlist intentionally by skipping and same behavior popped up.

**Comment by Nosskirneh** [comment]
Thanks for the bug report! Fixed in beta 9.
