### ISSUE TITLE
title color of next track

### ISSUE THREAD

**Issue by lovety111** [Nosskirneh/NextUp-Public#21]
![64E63EB3-6196-484A-AE65-30067147EB5B](https://user-images.githubusercontent.com/51091752/58431294-affa7580-80df-11e9-98be-5c8815012d16.jpeg)
When using NextUp 2 with Sylph the title color of the next track is in black. Is there a way to make it white? or i can just choose whatever color i want? I am using an iPhone 8 in iOS 12.1.2 with Spotify

**Comment by Nosskirneh** [comment]
Hi! Are you perhaps using ColorFlow? I've seen reports of this before but I can't seem to reproduce it. If you are using ColorFlow, please let me know what settings you have. NextUp 2 never sets the color to black.

**Comment by lovety111** [comment]
yes, i am using colorflow4 and for the settings please see below
![72A619B4-619E-41EE-A733-42E9D8BE9606](https://user-images.githubusercontent.com/51091752/59122727-1019d300-898e-11e9-9aed-c3687d9f450b.png)
![DEA68474-2089-4786-9C15-A85D1F2D9D23](https://user-images.githubusercontent.com/51091752/59122729-10b26980-898e-11e9-8a73-c0f999e12b91.png)
![CBBD5C9A-28B0-40A3-B60B-D37BBAC320B5](https://user-images.githubusercontent.com/51091752/59122730-10b26980-898e-11e9-8eae-cc91dfa89b19.png)
![0B54E2F0-571E-4C0B-AFF9-41CD5FF5D79A](https://user-images.githubusercontent.com/51091752/59122731-10b26980-898e-11e9-971c-31e54fa0b5cb.png)

**Comment by Nosskirneh** [comment]
Thank you, I'm finally able to reproduce the issue. Will look into it.

**Comment by Nosskirneh** [comment]
Sorry about the delay. This has been fixed in beta12 of NextUp 2 and beta 5 of NextUp for iOS 11.
