### ISSUE TITLE
next track title has been cut off while using Nereid

### ISSUE THREAD

**Issue by lovety111** [Nosskirneh/NextUp-Public#22]
![99A5A8FE-719D-4BB7-8C30-6950E145D0C0](https://user-images.githubusercontent.com/51091752/58445007-5e78d780-812d-11e9-94f8-1ae58ea4fd0c.jpeg)

I am using iPhone 8 in iOS 12.1.2 with Spotify

**Comment by Nosskirneh** [comment]
This is not an issue of NextUp but rather Nereid (although I haven't seen this issue with that combination). Are you perhaps using an old version of Sylph? Anyway, there is nothing NextUp can do about this, something else is hooking NextUp's view.
