### ISSUE TITLE
NextUp Not Working With EmojiPort

### ISSUE THREAD

**Issue by s4mplexd** [Nosskirneh/NextUp-Public#24]
iPhone X (iOS 12.0)
Unc0ver 3.1.2

After multiple tests on figuring this out, I thought it would be a conflict with a lockscreen tweak so I disabled all my LS tweaks and NextUp never appeared. I then went on a random pick and after a few tries, I landed on EmojiPort and it's dependencies. I'm not sure why it doesn't work with that tweak but I hope this could be fixed.

**Comment by Nosskirneh** [comment]
Hmm, this is odd. I tried EmojiPort on my iOS 11 device, and NextUp works perfectly fine. Maybe it's a iOS 12.x EmojiPort thing. I only have devices on iOS 12.1.x so I'm unable to test :/

**Comment by Nosskirneh** [comment]
Poomsmart's conclusion was that EmojiAttributes made the clients of NextUp to not work. I don't think there is anything we can do about it sadly. Sorry.

**Comment by Nosskirneh** [comment]
Closing as neither Poomsmart or I can do anything about it, sadly. Sorry :/

**Comment by s4mplexd** [comment]
Hello Andreas,

I actually forgot all about this. Come to find out, I accidentally found a
solution that just works seamlessly.

I use EmojiPort for my emojis, of course, but I also use NextUp 2 and they
work. I tried this a few days ago and I just reinstalled the pckages, I
believe. I have the 12.1 emojis with NextUp 2 working fine now.

Best,
Kevin

**Comment by Nosskirneh** [comment]
Strange that it just started working. Glad it did though! Thanks for letting me know about it :)
Cheers!

**Comment by s4mplexd** [comment]
I appreciate your time. Keep up the great work! Well worth the money.
