### ISSUE TITLE
NextUp puts phone into safe mode

### ISSUE THREAD

**Issue by optimxl** [Nosskirneh/NextUp-Public#28]
I've disabled several other tweaks through iCleaner such as Sylph and narrowed it down to NextUp. Everytime I push play in Apple Music or anywhere else, my phone boots into safe mode. I just bought the license because the trial worked great :/

**Comment by Nosskirneh** [comment]
Hi!

I’m sorry to hear that. It sounds like you might have installed the wrong NextUp package, but I don’t know for sure. Make sure you’re running NextUp 2 if using iOS 12. If the package is correct, please attach a crash report.

**Comment by optimxl** [comment]
I checked and I have NextUp 1. I'm on iOS 12. However, I purchased a license for NextUp 1 yesterday and NextUp 2 is saying it can't recognize my email. I'm happy to send the transaction ID and email used.

**Comment by Nosskirneh** [comment]
Someone recently emailed me about this – are you the same guy? Either way, please do email me with the info and I'll help you!

**Comment by optimxl** [comment]
I just read your emails and it worked. For some reason it registered under my alternate email. I really appreciate the speedy replies and assistance.
