### ISSUE TITLE
Settings page crash

### ISSUE THREAD

**Issue by ghost** [Nosskirneh/NextUp-Public#29]
Settings app crashes when scrolling down to the bottom of NextUp 2’s settings.

iPhone XR, iOS 13.3, unc0ver 4.0.3, NextUp 2 1.3.1.

![Screen recording of the issue](https://i.imgur.com/H28EgyN.mp4)

**Comment by Nosskirneh** [comment]
Thanks for reporting! Please send me the crash log.

**Comment by ghost** [comment]
OK, got it: https://x0.at/xLa.ips

**Comment by Nosskirneh** [comment]
Thanks! That unfortunate didn’t give any clues. If you disable all other tweaks using iCleaner Pro, does the crashing stop?

**Comment by ghost** [comment]
It still crashes: https://x0.at/BpS.ips

**Comment by Nosskirneh** [comment]
Does [the previous build](https://www.dropbox.com/s/jkgqgho16zhqc21/se.nosskirneh.nextup2_1.2_iphoneos-arm.deb?dl=0) work?

**Comment by ghost** [comment]
Yeah, that one seems to work.

**Comment by Nosskirneh** [comment]
Okay... I’ll send you a build in a while with some changes from the latest build and see if that works. I think this is the iOS 11.2 SDK causing issues on arm64e for some reason.

**Comment by Nosskirneh** [comment]
Could you please try [this build](https://www.dropbox.com/s/3j4h8blmvt3ihxn/se.nosskirneh.nextup2_1.3.2~b1_iphoneos-arm.deb?dl=0)? It's the same code as 1.3.1 but compiled with the iOS 9.2 SDK.

**Comment by ghost** [comment]
That one crashes again. https://x0.at/g3l.ips

**Edit**: With NextUp only: https://x0.at/6Xt.ips

**Comment by Nosskirneh** [comment]
Those crash logs say a bit more, but it points to a method crashing that should only be called when toggling support for specific apps (and not scrolling through the settings without toggling anything). I'm not sure why that would happen :/

Could you please try [this build](https://www.dropbox.com/s/ed8d8m03kyq02xj/se.nosskirneh.nextup2_1.3.2~b2_iphoneos-arm.deb?dl=0)? I don't think there's a difference in the syntax used, but doesn't hurt to try...

Have you disabled any clients btw?

**Comment by ghost** [comment]
Yeah, I'm pretty new to JB so the first time I just pulled out the crash logs with Filza, in meantime I installed a version of the CrashReporter app compatible with iOS 13. I guess the symbolicated logs it creates are more helpful.

Still the same crash with this build: https://x0.at/f3-.ips

I haven't disabled any of them, I only have Spotify and Apple Music installed but all the app toggles are on.

**Comment by Nosskirneh** [comment]
I was able to reproduce the crash. It only happens when not having a full license and it is caused by the cells being reused.

[This build](https://www.dropbox.com/s/dynt78h4eyaaka0/se.nosskirneh.nextup2_1.3.2~b3_iphoneos-arm.deb?dl=0) should fix it. Let me know if it wouldn't work.

**Comment by ghost** [comment]
That works, thanks. I'll be sure to buy a license :)

**Comment by Nosskirneh** [comment]
Happy to hear! Thanks for testing and providing crash logs! :)
