### ISSUE TITLE
Spotify freezing when opening

### ISSUE THREAD

**Issue by keshavbabu** [Nosskirneh/NextUp-Public#31]
I opened Spotify and either it hangs at the Spotify logo splash screen or it opens it to the main screen and doesn’t register any touches

**Comment by Nosskirneh** [comment]
I can’t reproduce this. I suspect it to be another tweak. If you disable all other tweaks using iCleaner Pro, does it still freeze when opening Spotify?

**Comment by Nick663** [comment]
Got the same problem also with Tidal and the standard-Music-App.

The problem occured for me after my Trial ended.

**Comment by Nosskirneh** [comment]
Thanks for the information. I am now able to reproduce it. I fear it was the change from RocketBootstrap that caused this. I will look into it!

**Comment by Nosskirneh** [comment]
I identifier the issue. This should work.

https://www.dropbox.com/s/ijdxhu7lzuykox9/se.nosskirneh.nextup2_1.3.3~b1_iphoneos-arm.deb?dl=0

Thanks a lot for reporting!

**Comment by Nick663** [comment]
That fixed the issue. Music Apps work again.

**Comment by Nosskirneh** [comment]
TIDAL also?

**Comment by Nick663** [comment]
That's what I tried to say with App**s**. It works on both :]

**Comment by Nosskirneh** [comment]
Ah, sorry. I missed the "s" and thought you only meant the Music app... All good, thanks for testing! :)
