### ISSUE TITLE
Next up 2 randomly disappear/stop working

### ISSUE THREAD

**Issue by PuniTsubakiHime** [Nosskirneh/NextUp-Public#39]
It always stop working after a while and requires a restoring. It can be working at first, after a few songs, it would disappear.

Currently on iOS 13.3 iPhone 8 Plus rocketbootstrap 1.0.7

**Comment by PuniTsubakiHime** [comment]
Is there other way to solve it apart from respringing it because RBS randomly stop working?

**Comment by PuniTsubakiHime** [comment]
RBS 1.0.8 also seems to have the same problem.

**Comment by Nosskirneh** [comment]
NextUp 2 doesn't use RocketBootstrap anymore. Please try disabling all other tweaks. What jailbreak are you using, checkra1n or unc0ver?

**Comment by PuniTsubakiHime** [comment]
Checkra1n
After testing, I think it might be dyadic causing the problem.

**Comment by PuniTsubakiHime** [comment]
Checkra1n.
I will need some time to test because it only happens after a while, mostly not using it for a while causes it to happen.

**Comment by PuniTsubakiHime** [comment]
I think it’s snowboard and it’s extensions. I’m using font, settings and status bar extensions. I’ve used with snowboard fully disabled for 2 days, and I haven’t run into NextUp2 disappearing yet.
