### ISSUE TITLE
Displays currently playing song if the track was completed and not skipped. 

### ISSUE THREAD

**Issue by jpslsu21** [Nosskirneh/NextUp-Public#44]
iPhone XS Max 13.5 uncover

After finishing a song, the nextup track won’t change and display the currently playing song.  It doesn’t happen when you skip forward, but only after a song ends.

**Comment by Nosskirneh** [comment]
You’re right, I’ll look into this. The support for Apple Music was rewritten in 1.3.5 to fix another bug (not being able to select a track in the queue). In the meantime, you could use this version: https://www.dropbox.com/s/72yd79wglcmn1h6/se.nosskirneh.nextup2_1.3.4-1_iphoneos-arm.deb?dl=0

**Comment by jpslsu21** [comment]
Thanks for the quick response. Will continue to use 1.3.4-1 until a new fix comes out.  Appreciate your help and the great tweak!

**Comment by Nosskirneh** [comment]
Could you try [this one](https://www.dropbox.com/s/naa1pbexazywcbk/se.nosskirneh.nextup2_1.3.5-1_iphoneos-arm.deb?dl=0), please? Works on my end, but I'd like to have some more confirmation before submitting to BigBoss.

**Comment by jpslsu21** [comment]
The bugs seem to be gone. Yet, it feels like it’s taking longer to switch songs. There is more of a delay between changing songs than 1.3.4-1 and 1.3.5. However, it does change songs after a song ends and no longer overlaps the skip button.

**Comment by Nosskirneh** [comment]
Alright, any difference in [this build](https://www.dropbox.com/s/xv4ygsbaud31p0z/se.nosskirneh.nextup2_1.3.5-1~a1_iphoneos-arm.deb?dl=0)?

**Comment by jpslsu21** [comment]
That build is working perfect. No more lag and the other bugs are gone.

**Comment by Nosskirneh** [comment]
Perfect, I'll go ahead and submit it as 1.3.5-1 to BigBoss. Thanks for reporting and testing!
