### ISSUE TITLE
Misaligned on RTL languages om iOS 13.4+

### ISSUE THREAD

**Issue by Aransh** [Nosskirneh/NextUp-Public#45]
![image](https://user-images.githubusercontent.com/11724502/87482169-84b34c80-c639-11ea-8825-4abf92faa2cd.jpeg)

**Comment by Nosskirneh** [comment]
Thanks for reporting! It works for me running 1.3.6 on iOS 13.5. Could you verify if this is the case also for you?
1.3.6 could be found on [my repo](https://henrikssonbrothers.com/cydia/repo/).
![IMG_1383](https://user-images.githubusercontent.com/16581727/87482627-1f0f9200-c632-11ea-8dec-941e18e1a3c7.PNG)

**Comment by Aransh** [comment]
@Nosskirneh yes! 1.3.6 seems to have fixed it! Thank you very much.
I've seen the new update but didn't see this mentioned in the changelog so I figured I'd open an issue.

**Comment by Nosskirneh** [comment]
Ah, I think the support for 13.5 (1.3.5) where the the track label no longer going above the skip button fixed the same issue. Glad it has been resolved!
