### ISSUE TITLE
Spotify crash on attempting to skip song

### ISSUE THREAD

**Issue by beanth** [Nosskirneh/NextUp-Public#5]
Only happened once, tweak otherwise working perfect. Crash log for spotify: https://pastebin.com/raw/tt5FttAn

**Comment by Nosskirneh** [comment]
Not sure why the array is empty, but the crash will be solved in beta3. What will happen instead is that nothing will be skipped. I guess this doesn't happen that often. If it does for someone, feel free to reopen this.
