### ISSUE TITLE
Sylph issue

### ISSUE THREAD

**Issue by dongmin-dev** [Nosskirneh/NextUp-Public#53]
What app or process isn't working.
Not working with sylph tweak with my settings

App version (if applicable), iOS version and NextUp version.
Apple Music, iOS 13.5, Latest build of NextUp2

How to reproduce (if not obvious steps).
Set to this setting at sylph and Slimmed mode
sylph settings: https://share.icloud.com/photos/0I_-gVBr3l4Id6vd3BuOT2ZcQ

Crash report if such exists.
none

**Comment by dongmin-dev** [comment]
The bug shows like this: https://share.icloud.com/photos/0DmIAXu6MDggMB4TftadpCARw

**Comment by Nosskirneh** [comment]
If I remember correctly, you should not hide artwork in both Sylph and NextUp; doing so will move the view twice as much. Try disabling it in NextUp.

**Comment by dongmin-dev** [comment]
Worked like magic 👍👍 Thank you so much for quick response and help!
