### ISSUE TITLE
Can’t get it to work

### ISSUE THREAD

**Issue by rynebarber** [Nosskirneh/NextUp-Public#9]
Do you know if there are any tweaks this is not compatible with? I have purchased the license but I can’t seem to get it to work. I’ve tried reinstalling and removing tweaks that affect Spotify and the lock screen but none have been effective.

**Comment by Nosskirneh** [comment]
What version of RocketBootstrap do you have? I forgot to put the correct version as a dependency. You need to have 1.0.7 or higher if you're on iOS 12.

If that isn't the culprit, please attach a tweak list.

**Comment by rynebarber** [comment]
That was it, thanks a lot for the prompt response and this tweak!

**Comment by Nosskirneh** [comment]
Glad to hear! Thanks for the support! :)
